// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.26.0
// source: tenant/tenant.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "tenant";

export interface FindTenantByNameRequest {
  name: string;
}

export interface RetrieveTenantRequest {
  id: string;
}

export interface CreateTenantRequest {
  name: string;
  displayName: string;
  description: string;
  region: string;
  environment: string;
  jwtConfiguration: string;
}

export interface Tenant {
  id: string;
  name: string;
  displayName: string;
  description: string;
  region: string;
  environment: string;
  jwtConfiguration: string;
}

export const TENANT_PACKAGE_NAME = "tenant";

export interface TenantServiceClient {
  create(request: CreateTenantRequest): Observable<Tenant>;

  retrieve(request: RetrieveTenantRequest): Observable<Tenant>;

  findByName(request: FindTenantByNameRequest): Observable<Tenant>;
}

export interface TenantServiceController {
  create(request: CreateTenantRequest): Promise<Tenant> | Observable<Tenant> | Tenant;

  retrieve(request: RetrieveTenantRequest): Promise<Tenant> | Observable<Tenant> | Tenant;

  findByName(request: FindTenantByNameRequest): Promise<Tenant> | Observable<Tenant> | Tenant;
}

export function TenantServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["create", "retrieve", "findByName"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TenantService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TenantService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TENANT_SERVICE_NAME = "TenantService";
