version: '3.5'
services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: 'mysql'
      DRIVER: 'mysql'
      DB_PORT: 3306
      DB_USER: 'me'
      DB_PASSWORD: 'secret'
      DB_DATABASE: 'authok_mgmt'
      REDIS_HOST: 'redis'
    ports:
      - 3003:3003
    networks:
      biz:
        aliases:
          - api-server
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'me'
      MYSQL_PASSWORD: 'secret'
    ports:
      - 3306:3306
    volumes:
      - "~/opt/mysql:/var/lib/mysql"
    networks:
      biz:
        aliases:
          - mysql
  postgres:
    image: postgres:latest
    volumes:
      - ~/opt/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: authok
      POSTGRES_PASSWORD: postgres
    networks:
      biz:
        aliases:
          - postgres
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: root@authok.io
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      biz:
        aliases:
          - pgadmin
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
    networks:
      biz:
        aliases:
          - redis
networks:
  biz:
    name: biz
    driver: bridge
