export const managementApiScopes = [
  { value: 'read:groups', description: 'Read Groups' },
  { value: 'update:groups', description: 'Update Groups' },
  { value: 'delete:groups', description: 'Delete Groups' },
  { value: 'create:groups', description: 'Create Groups' },
  { value: 'read:client_grants', description: 'Read Client Grants' },
  { value: 'create:client_grants', description: 'Create Client Grants' },
  { value: 'delete:client_grants', description: 'Delete Client Grants' },
  { value: 'update:client_grants', description: 'Update Client Grants' },
  { value: 'read:users', description: 'Read users' },
  { value: 'update:users', description: 'Update Users' },
  { value: 'delete:users', description: 'Delete Users' },
  { value: 'create:users', description: 'Create Users' },
  { value: 'read:users_app_metadata', description: 'Read Users App Metadata' },
  { value: 'update:users_app_metadata', description: 'Update Users App Metadata' },
  { value: 'delete:users_app_metadata	', description: 'Delete Users App Metadata' },
  { value: 'create:users_app_metadata', description: 'Create Users App Metadata' },
  { value: 'read:user_custom_blocks', description: 'Read Custom User Blocks' },
  { value: 'create:user_custom_blocks', description: 'Create Custom User Blocks' },
  { value: 'delete:user_custom_blocks', description: 'Delete Custom User Blocks' },
  { value: 'create:user_tickets', description: 'Create User Tickets' },
  { value: 'read:clients', description: 'Read Clients' },
  { value: 'update:clients', description: 'Update Clients' },
  { value: 'delete:clients', description: 'Delete Clients' },
  { value: 'create:clients', description: 'Create Clients' },
  { value: 'read:client_keys', description: 'Read Client Keys' },
  { value: 'update:client_keys', description: 'Update Client Keys' },
  { value: 'delete:client_keys', description: 'Delete Client Keys' },
  { value: 'create:client_keys', description: 'Create Client Keys' },
  { value: 'read:connections', description: 'Read Connections' },
  { value: 'update:connections', description: 'Update Connections' },
  { value: 'delete:connections', description: 'Delete Connections' },
  { value: 'create:connections', description: 'Create Connections' },
  { value: 'read:resource_servers', description: 'Read Resource Servers' },
  { value: 'update:resource_servers', description: 'Update Resource Servers' },
  { value: 'delete:resource_servers', description: 'Delete Resource Servers' },
  { value: 'create:resource_servers', description: 'Create Resource Servers' },
  { value: 'read:device_credentials', description: 'Read Device Credentials' },
  { value: 'update:device_credentials', description: 'Update Device Credentials' },
  { value: 'delete:device_credentials', description: 'Delete Device Credentials' },
  { value: 'create:device_credentials', description: 'Create Device Credentials' },
  { value: 'read:rules', description: 'Read Rules' },
  { value: 'update:rules', description: 'Update Rules' },
  { value: 'delete:rules', description: 'Delete Rules' },
  { value: 'create:rules', description: 'Create Rules' },
  { value: 'read:rules_configs', description: 'Read Rules Configs' },
  { value: 'update:rules_configs', description: 'Update Rules Configs' },
  { value: 'delete:rules_configs', description: 'Delete Rules Configs' },
  { value: 'read:hooks', description: 'Read Hooks' },
  { value: 'update:hooks', description: 'Update Hooks' },
  { value: 'delete:hooks', description: 'Delete Hooks' },
  { value: 'create:hooks', description: 'Create Hooks' },
  { value: 'read:actions', description: 'Read Actions' },
  { value: 'update:actions', description: 'Update Actions' },
  { value: 'delete:actions', description: 'Delete Actions' },
  { value: 'create:actions', description: 'Create Actions' },
  { value: 'read:email_provider', description: 'Read Email Provider' },
  { value: 'update:email_provider', description: 'Update Email Provider' },
  { value: 'delete:email_provider', description: 'Delete Email Provider' },
  { value: 'create:email_provider', description: 'Create Email Provider' },
  { value: 'blacklist:tokens', description: 'Blacklist Tokens' },
  { value: 'read:stats', description: 'Read Stats' },
  { value: 'read:insights', description: 'Read Insights' },
  { value: 'read:tenant_settings', description: 'Read Tenant Settings' },
  { value: 'update:tenant_settings', description: 'Update Tenant Settings' },
  { value: 'read:logs', description: 'Read Logs' },
  { value: 'read:logs_users', description: 'Read logs relating to users' },
  { value: 'read:shields', description: 'Read Shields' },
  { value: 'create:shields', description: 'Create Shields' },
  { value: 'update:shields', description: 'Update Shields' },
  { value: 'delete:shields', description: 'Delete Shields' },
  { value: 'read:anomaly_blocks', description: 'Read Anomaly Detection Blocks' },
  { value: 'delete:anomaly_blocks', description: 'Delete Anomaly Detection Blocks' },
  { value: 'update:triggers', description: 'Update Triggers' },
  { value: 'read:triggers', description: 'Read Triggers' },
  { value: 'read:grants', description: 'Read User Grants' },
  { value: 'delete:grants', description: 'Delete User Grants' },
  { value: 'read:guardian_factors', description: 'Read Guardian factors configuration' },
  { value: 'update:guardian_factors', description: 'Update Guardian factors' },
  { value: 'read:guardian_enrollments', description: 'Read Guardian enrollments' },
  { value: 'delete:guardian_enrollments', description: 'Delete Guardian enrollments' },
  { value: 'create:guardian_enrollment_tickets', description: 'Create enrollment tickets for Guardian' },
  { value: 'read:user_idp_tokens', description: 'Read Users IDP tokens' },
  { value: 'create:passwords_checking_job', description: 'Create password checking jobs' },
  { value: 'delete:passwords_checking_job', description: 'Deletes password checking job and all its resources' },
  { value: 'read:custom_domains', description: 'Read custom domains configurations' },
  { value: 'delete:custom_domains', description: 'Delete custom domains configurations' },
  { value: 'create:custom_domains', description: 'Configure new custom domains' },
  { value: 'update:custom_domains', description: 'Update custom domain configurations' },
  { value: 'read:email_templates', description: 'Read email templates' },
  { value: 'create:email_templates', description: 'Create email templates' },
  { value: 'update:email_templates', description: 'Update email templates' },
  { value: 'read:mfa_policies', description: 'Read Multifactor Authentication policies' },
  { value: 'update:mfa_policies', description: 'Update Multifactor Authentication policies' },
  { value: 'read:roles', description: 'Read roles' },
  { value: 'create:roles', description: 'Create roles' },
  { value: 'delete:roles', description: 'Delete roles' },
  { value: 'update:roles', description: 'Update roles' },
  { value: 'read:prompts', description: 'Read prompts settings' },
  { value: 'update:prompts', description: 'Update prompts settings' },
  { value: 'read:branding', description: 'Read branding settings' },
  { value: 'update:branding', description: 'Update branding settings' },
  { value: 'delete:branding', description: 'Delete branding settings' },
  { value: 'read:log_streams', description: 'Read log_streams' },
  { value: 'create:log_streams', description: 'Create log_streams' },
  { value: 'delete:log_streams', description: 'Delete log_streams' },
  { value: 'update:log_streams', description: 'Update log_streams' },
  { value: 'create:signing_keys', description: 'Create signing keys' },
  { value: 'read:signing_keys', description: 'Read signing keys' },
  { value: 'update:signing_keys', description: 'Update signing keys' },
  { value: 'read:limits', description: 'Read entity limits' },
  { value: 'update:limits', description: 'Update entity limits' },
  { value: 'create:role_members', description: 'Create role members' },
  { value: 'read:role_members', description: 'Read role members' },
  { value: 'delete:role_members', description: 'Delete role members' },
  { value: 'read:entitlements', description: 'Read entitlements' },
  { value: 'read:attack_protection', description: 'Read attack protection' },
  { value: 'update:attack_protection', description: 'Update attack protection' },
  { value: 'read:organizations', description: 'Read Organizations' },
  { value: 'update:organizations', description: 'Update Organizations' },
  { value: 'create:organizations', description: 'Create Organizations' },
  { value: 'delete:organizations', description: 'Delete Organizations' },
  { value: 'create:organization_members', description: 'Create organization members' },
  { value: 'read:organization_members', description: 'Read organization members' },
  { value: 'delete:organization_members', description: 'Delete organization members' },
  { value: 'create:organization_connections', description: 'Create organization connections' },
  { value: 'read:organization_connections', description: 'Read organization connections' },
  { value: 'update:organization_connections', description: 'Update organization connections' },
  { value: 'delete:organization_connections', description: 'Delete organization connections' },
  { value: 'create:organization_member_roles', description: 'Create organization member roles' },
  { value: 'read:organization_member_roles', description: 'Read organization member roles' },
  { value: 'delete:organization_member_roles', description: 'Delete organization member roles' },
  { value: 'create:organization_invitations', description: 'Create organization invitations' },
  { value: 'read:organization_invitations', description: 'Read organization invitations' },
  { value: 'delete:organization_invitations', description: 'Delete organization invitations' },
];