name: Docker Image CI

on:
  push:
    tags:
      - '*'
  release:
    types:
      - "published"

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "echoagi/authok"
      # GitHub Actions expressions don't have great conditional support, so
      # writing a ternary expression looks a lot like bash. In Python, this
      # would read as:
      #     github.event.release.tag_name if github.event_name == 'release' else 'latest'
      #     https://docs.github.com/en/actions/learn-github-actions/expressions
      IMAGE_TAG: "${{ github.event_name == 'release' && github.event.release.tag_name || github.ref_name || 'latest' }}"

    steps:
    - uses: actions/checkout@v4
    - name: "DockerHub login"
      uses: "docker/login-action@v2"
      with:
        username: "${{secrets.DOCKER_USER}}"
        password: "${{secrets.DOCKER_PASS}}"
    - name: Build and push to Docker hub
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ IMAGE_NAME }}:${{ IMAGE_TAG }}
          ${{ IMAGE_NAME }}:latest