name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "echoagi/authok"
      # GitHub Actions expressions don't have great conditional support, so
      # writing a ternary expression looks a lot like bash. In Python, this
      # would read as:
      #     github.event.release.tag_name if github.event_name == 'release' else 'latest'
      #     https://docs.github.com/en/actions/learn-github-actions/expressions
      IMAGE_TAG: "${{ github.event_name == 'release' && github.event.release.tag_name || 'latest' }}"

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --file Dockerfile -t "${IMAGE_NAME}:${IMAGE_TAG}" .
    - name: "DockerHub login"
      uses: "docker/login-action@v2"
      with:
        username: "${{secrets.DOCKER_USER}}"
        password: "${{secrets.DOCKER_PASS}}"
    - name: "Push to DockerHub and GHCR"
      run: |
        docker push "${IMAGE_NAME}:${IMAGE_TAG}"
